### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by theel0ja** [hishamco/vRedis#1]
Template: https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

**Comment by hishamco** [comment]
It's long time I didn't update this project, I will try to add the `.gitignore` file soon
thanks @theel0ja

**Comment by hishamco** [comment]
Fixed in https://github.com/hishamco/vRedis/commit/ee0becddc2eea97228289b368ad18d71ee889035
